---
en: push
jobs:
  build-node:
    runs-on: ubuntu-lastest
    container: node:19.3.0
    steps:
      - uses: actions/checkout@v3
      run: |
        node --version
        npm --version
        npm install
        node sever.js