on:
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string
jobs:
  print-username:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input name to STDOUT 
      - uses: actions/checkout@v3
      - run: |
            node --version
            npm --version
            npm install
            node sever.js
